spring:
  application:
    name: member

  mvc:
    cors:
      mappings:
        "/api/**":
          allowed-origins: "https://gdgoc-seoultech.vercel.app"
          allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
          allowed-headers: "*"
          allow-credentials: true


  config:
    import: "optional:file:.env[.properties]"
  # =========================
  # AWS s3
  # =========================
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:}
        secret-key: ${AWS_SECRET_KEY:}
      region:
        static: ${AWS_S3_REGION:ap-northeast-2}
      s3:
        bucket: ${AWS_S3_BUCKET:}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # =========================
  # Security (Google OAuth2)
  # =========================
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

  # =========================
  # Datasource
  # =========================
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:gdg_post}?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # =========================
  # JPA
  # =========================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8080
  address: 127.0.0.1
  forward-headers-strategy: framework

logging:
  level:
    org.hibernate.SQL: debug
